name: api_client
version: 1.0.0
description: OpenAPI API client
homepage: homepage

resolution: workspace
environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  dio: ^5.9.0
  copy_with_extension: ^9.1.1
  json_annotation: '^4.9.0'

dev_dependencies:
  build_runner: ^2.7.1
  json_serializable: '^6.9.3'
  copy_with_extension_gen: ^9.1.1
  test: '^1.16.0'
