name: akademove
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

resolution: workspace

environment:
  sdk: ^3.10.1

dependencies:
  api_client:
    path: ../../gen/dart/api_client
  flutter:
    sdk: flutter
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  const_date_time: ^1.2.1
  dio: ^5.9.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.5.0
  flutter_polyline_points: ^3.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  flutter_timezone: ^5.0.1
  gal: ^2.3.2
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  get_it: ^9.1.0
  go_router: ^17.0.0
  google_maps_flutter: ^2.14.0
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  logger: ^2.6.2
  path_provider: ^2.1.5
  shadcn_flutter: ^0.0.47
  shared_preferences: ^2.5.3
  syncfusion_flutter_charts: ^31.2.12
  syncfusion_flutter_gauges: ^31.2.12
  timezone: ^0.10.1
  web_socket_channel: ^3.0.3
  permission_handler: ^12.0.1
  url_launcher: ^6.3.1
  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.10.4
  flutter_gen_runner: ^5.12.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bg/
    - assets/images/character/
    - assets/images/hero/
    - assets/icons/

flutter_gen:
  output: lib/gen/
  integrations:
    image: true
    flutter_svg: true
