name: akademove
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  openapi_generator_annotations: ^6.1.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  openapi_generator: ^6.1.0
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
